"""Convert the human-readable DNS records file to BIND zone format
(RFC 1035) for Hostinger's Import dialog.

Reads from out/atalsolidrocks-dns-records.txt + the resend_domain_id list
in profiles/atalsolidrocks.json and writes out/atalsolidrocks.zone.

Run:
    py scripts/dns-records-to-bind.py
"""
from __future__ import annotations

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "out" / "atalsolidrocks-dns-records.txt"
DST = REPO / "out" / "atalsolidrocks.zone"
ORIGIN = "atalsolidrocks.io."


def main() -> int:
    src = SRC.read_text(encoding="utf-8")
    out_lines: list[str] = []
    out_lines.append(f"; Zone file for {ORIGIN}")
    out_lines.append(f"; Generated by dns-records-to-bind.py")
    out_lines.append(f"; Import via Hostinger > DNS > Manage DNS records > Import")
    out_lines.append("")
    out_lines.append(f"$ORIGIN {ORIGIN}")
    out_lines.append("$TTL 3600")
    out_lines.append("")

    current_sub: str | None = None
    for line in src.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("## "):
            current_sub = s[3:].strip()
            out_lines.append(f"; ── {current_sub} ──")
            continue
        # Records look like: "TYPE  NAME  CONTENT" with variable spacing
        parts = s.split(None, 2)
        if len(parts) < 3:
            continue
        rec_type, name, content = parts[0], parts[1], parts[2]
        if rec_type == "TXT":
            # TXT content must be quoted. Internal double-quotes get escaped.
            esc = content.replace("\\", "\\\\").replace('"', '\\"')
            out_lines.append(f'{name}\tIN\tTXT\t"{esc}"')
        elif rec_type == "MX":
            # MX content already has "priority target" format. Add trailing
            # dot to target so BIND treats it as absolute.
            mx_parts = content.split(None, 1)
            if len(mx_parts) == 2:
                prio, target = mx_parts
                if not target.endswith("."):
                    target = target + "."
                out_lines.append(f"{name}\tIN\tMX\t{prio} {target}")
            else:
                out_lines.append(f"{name}\tIN\tMX\t{content}")
        elif rec_type == "CNAME":
            target = content if content.endswith(".") else content + "."
            out_lines.append(f"{name}\tIN\tCNAME\t{target}")
        elif rec_type == "A":
            out_lines.append(f"{name}\tIN\tA\t{content}")
        elif rec_type == "AAAA":
            out_lines.append(f"{name}\tIN\tAAAA\t{content}")
        else:
            out_lines.append(f"{name}\tIN\t{rec_type}\t{content}")

    out_lines.append("")
    DST.parent.mkdir(exist_ok=True)
    DST.write_text("\n".join(out_lines), encoding="utf-8")
    n_rec = sum(1 for l in out_lines if "\tIN\t" in l)
    print(f"Wrote {n_rec} records to {DST}")
    print(f"\nFirst 20 lines:")
    for l in out_lines[:20]:
        print(f"  {l}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
